School.PL/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School.DAL.Models;
using School.PL.Helper.CustomAttributes;
using School.PL.Models.RoleView;

namespace School.PL.Controllers
{
    [CustomAuthorize("Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<UserController> _logger;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(
            RoleManager<IdentityRole> roleManager,
            ILogger<UserController> logger,
            UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _logger = logger;
            _userManager = userManager;
        }

        // GET: RoleController/Index
        public async Task<IActionResult> Index(string searchInput)
        {
            var Role=Enumerable.Empty<RoleViewModel>();
            if (string.IsNullOrEmpty(searchInput))
            {
                Role =await _roleManager.Roles.Select(R => new RoleViewModel()
                {
                    Id=Guid.Parse(R.Id),
                    RoleName=R.Name
                }).ToListAsync();
            }
            else
            {
                Role = await _roleManager.Roles
                    .Where(R => R.Name
                    .ToLower().Contains(searchInput.ToLower()))
                    .Select(R => new RoleViewModel()
                    {
                        Id = Guid.Parse(R.Id),
                        RoleName = R.Name
                    }).ToListAsync();
            }
            return View(Role);
        }

        // GET: RoleController/Details
        [HttpGet]
        public async Task<IActionResult> Details(Guid? id, string viewname = "Details")
        {
            var Role = await _roleManager.FindByIdAsync(id.ToString());
            if (Role is null)
            {
                return NotFound();
            }
            if (viewname == "Update")
            {

                var RoleModel = new RoleViewModel
                {
                    Id=Guid.Parse(Role.Id),
                    RoleName =Role.Name
                };
                return View(viewname, RoleModel);
            }
            return View(viewname, Role); 
        }

        // GET: RoleController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoleController/Create
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole()
                {
                    Name = model.RoleName
                };
                await _roleManager.CreateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: RoleController/Update
        [HttpGet]
        public async Task<IActionResult> Update(Guid? id)
        {
            return await Details(id, "Update");

        }

        // POST: RoleController/Update
        [HttpPost]
        public async Task<IActionResult> Update(Guid? id, RoleViewModel roleViewModel)
        {
            if (id != roleViewModel.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var Role = await _roleManager.FindByIdAsync(id.ToString());
                if (Role is null)
                {
                    return NotFound();
                }
                Role.Name = roleViewModel.RoleName;
                Role.NormalizedName = roleViewModel.RoleName.ToUpper();
                var res = await _roleManager.UpdateAsync(Role);
                if (res.Succeeded)
                {
                    _logger.LogInformation("user updated successfully");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    _logger.LogInformation("user updated Failed");
                    return View(roleViewModel);

                }
            }

            return View(roleViewModel);
        }

        // GET: RoleController/Delete
        public async Task<IActionResult> Delete(Guid? id)
        {
            try
            {
                var user = await _roleManager.FindByIdAsync(id.ToString());
                if (user is null)
                {
                    return NotFound();
                }
                var res = await _roleManager.DeleteAsync(user);
                if (res.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var i in res.Errors)
                {
                    _logger.LogError(i.Description);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
            }


            return RedirectToAction(nameof(Index));


        }

        // GET: RoleController/AddOrRemoveUsers
        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(Guid? roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId.ToString());
            if (role is null)
            {
                return NotFound();
            }
            ViewData["RoleID"]= roleId;
            var usersInRole=new List<UserInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();
            foreach (var user in users)
            {
                var userInRole = new UserInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected=false;
                }
                usersInRole.Add(userInRole);
            }
            return View(usersInRole);
        }

        // POST: RoleController/AddOrRemoveUsers
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(Guid? roleId, List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId.ToString());
            if (role is null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appuser = await _userManager.FindByIdAsync(user.UserId);
                    if (appuser is not null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.AddToRoleAsync(appuser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appuser, role.Name);

                        }

                    }

                }
                return RedirectToAction("Update", new { id = roleId });
            }
            return View(users);
        } 
    }
}

School.PL/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using School.PL.Helper.CustomAttributes;
using School.PL.Helper.Services;
using School.PL.Models.UserView;

namespace School.PL.Controllers
{
    [CustomAuthorize("Admin")]
    public class UserController : Controller
    {
        private readonly IUserServices _userServices;
        private readonly IClassesServices _classesServices;
        private ILogger<UserController> _logger;

        public UserController(ILogger<UserController> logger,IUserServices userServices,IClassesServices classesServices)
        {
            _logger = logger;
            _userServices = userServices;
            _classesServices = classesServices;
        }

        // GET: UserController/Index
        public async Task<IActionResult> Index(string searchInput)
        {
            #region Index
            //var users=Enumerable.Empty<UserViewModel>();
            //if (string.IsNullOrEmpty(searchInput))
            //{
            //    users=await _userManager.Users.Select(U => new UserViewModel()
            //    {
            //        Id=Guid.Parse(U.Id),
            //        UserName=U.UserName,
            //        Email=U.Email,
            //        ClassName=U.Classes.Name
            //    }).ToListAsync();
            //}
            //else
            //{
            //    users=await _userManager.Users.Where(U => U.Email.ToLower()
            //                      .Contains(searchInput.ToLower()))
            //                      .Select(U => new UserViewModel()
            //                      {
            //                          Id = Guid.Parse(U.Id),
            //                          UserName = U.UserName,
            //                          Email = U.Email,
            //                          ClassName = U.Classes.Name
            //                      }).ToListAsync();

            //} 
            #endregion
            var user=await _userServices.GetAllUser(searchInput);
            return View(user);
        }

        // GET: UserController/Details
        public async Task<IActionResult> Details(Guid? id, string viewname = "Details")
        {
            if (id == null)
            {
                return BadRequest("Invalid user ID.");
            }

            var user = await _userServices.GetUserByIdAsync(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            if (viewname == "Update")
            {
                var userUpdateModel = await _userServices.GetUserUpdateViewModelAsync(id.Value);
                if (userUpdateModel == null)
                {
                    return NotFound();
                }
                return View(viewname, userUpdateModel);
            }

            return View(viewname, user);
            #region MyRegion
            //var user = await _userManager.FindByIdAsync(id.ToString());
            //if (user is null)
            //{
            //    return NotFound();
            //}
            //if (viewname == "Update")
            //{

            //    var UserModel = new UserUpdateViewModel
            //    {
            //        Id =Guid.Parse(user.Id),
            //        UserName = user.UserName
            //    };
            //    return View(viewname, UserModel);
            //}
            //return View(viewname, user); 
            #endregion

        }

        // GET: UserController/Update
        [HttpGet]
        public async Task<IActionResult> Update(Guid? id)
        {
            return await Details(id, "Update");

        }

        // POST: UserController/Update
        [HttpPost]
        public async Task<IActionResult> Update(Guid? id, UserUpdateViewModel appUserUpdate)
        {
            #region MyRegion
            //if (id != appUserUpdate.Id)
            //{
            //    return NotFound();
            //}
            //if (ModelState.IsValid)
            //{
            //    try
            //    {
            //        var user = await _userManager.FindByIdAsync(id.ToString());
            //        if (user is null)
            //        {
            //            return NotFound();
            //        }
            //        user.UserName = appUserUpdate.UserName;
            //        user.NormalizedUserName = appUserUpdate.UserName.ToUpper();
            //        var res = await _userManager.UpdateAsync(user);
            //        if (res.Succeeded)
            //        {
            //            _logger.LogInformation("user updated successfully");
            //            return RedirectToAction(nameof(Index));
            //        }
            //        else
            //        {
            //            _logger.LogInformation("user updated Failed");
            //            return View(appUserUpdate);

            //        }


            //    }
            //    catch (Exception ex)
            //    {
            //        _logger.LogInformation(ex.Message);

            //    }

            //}

            //return View(appUserUpdate); 
            #endregion

            if (id != appUserUpdate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var result = await _userServices.UpdateUserAsync(id.Value, appUserUpdate);

                if (result.Succeeded)
                {
                    _logger.LogInformation("User updated successfully");
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    _logger.LogWarning("User update failed");
                    ModelState.AddModelError(string.Empty, "Update failed");
                    return View(appUserUpdate);
                }
            }
            return View(appUserUpdate);
        }

        // GET: UserController/Delete
        public async Task<IActionResult> Delete(Guid id)
        {
            await _userServices.DeleteUserAsync(id);
            return RedirectToAction(nameof(Index));
            #region MyRegion
            //try
            //{
            //    var user = await _userManager.FindByIdAsync(id.ToString());
            //    if (user is null)
            //    {
            //        return NotFound();
            //    }
            //    var res = await _userManager.DeleteAsync(user);
            //    if (res.Succeeded)
            //    {
            //        return RedirectToAction(nameof(Index));
            //    }
            //    foreach (var i in res.Errors)
            //    {
            //        _logger.LogError(i.Description);
            //    }
            //}
            //catch (Exception ex)
            //{
            //    _logger.LogError(ex.Message);
            //}
            //return RedirectToAction(nameof(Index)); 
            #endregion
        }

        // GET: UserController/AssignToClassAsync
        [HttpGet]
        [CustomAuthorize("Admin")]
        public async Task<IActionResult> AssignToClassAsync()
        {
            var classes = await _classesServices.GetAllClassAsync();
            ViewData["Classes"] = new SelectList(classes, "Id", "Name");
            return View();
        }

        // POST: UserController/AssignToClassAsync
        [HttpPost]
        public async Task<IActionResult> AssignToClass(Guid? userId, Guid? classId)
        {
            if (userId is null || classId is null)
            {
                ModelState.AddModelError(string.Empty, "Invalid user or class.");
                return View();
            }
            var result = await _userServices.AssignUserToClassAsync(userId.Value, classId.Value);
            if (result)
            {
                return RedirectToAction(nameof(Success));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Failed to assign user to class.");
                return View();
            }
        }

        // A simple success view after assignment
        public IActionResult Success()
        {
            return View();
        }
    }
}
   

School.PL/Views/Shared/_AccountLayout.cshtml
<html lang="en">
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/Account.css" rel="stylesheet" />
</head>
<body class="align">

    @RenderBody()

</body>
</html>

School.PL/Views/Shared/_ButtonPartiaView.cshtml
@model Guid
<td><a asp-action="Details" asp-route-id="@Model"><i class="fa-solid fa-eye"></i></a></td>
<td><a asp-action="Update" asp-route-id="@Model"><i class="fa-solid fa-pen-to-square"></i></a></td>
<td><a asp-action="Delete" asp-route-id="@Model"><i class="fa-solid fa-trash"></i></a></td>

School.PL/Views/Shared/_Layout.cshtml
@using School.PL.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Classes" asp-action="Index">Classes</a>
                        </li>

                    </ul>
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav">

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        </ul>
                    }
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="SignOut">
                                    <button type="submit" class="nav-link btn btn-danger text-white">Sign Out</button>
                                </form>
                            </li>
                        </ul>
                    }else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <form  asp-controller="Account" asp-action="SignIn" method="get">
                                    <button type="submit" class="nav-link btn btn-danger text-white">SignIn</button>
                                </form>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - School.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>